// Automatically generated by astro-icon
// eb9080a58e8b93033adf9fe4394168de18c31e183cb47cfd4b39e8a5c72b7728

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "clock"
		| "email"
		| "mail-black"
		| "map"
		| "maps"
		| "phone"
		| "phone-black";
}