// Automatically generated by astro-icon
// 225ccc701a744d796e23fdfb737e99502381532c31240e859bd9bab244a71c28

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "clock"
		| "email"
		| "map"
		| "phone";
}